add step to check image version unique

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -31,6 +31,19 @@ jobs:
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
+      
+      - name: Ensure unique version tag
+        working-directory: apps/${{ inputs.application }}
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          APPLICATION: ${{ inputs.application }}
+        run: |
+          BUILD_VERSION="$(cat ./build/version)"
+          if docker manifest inspect "${ECR_REGISTRY}/yeahboi/apps/${APPLICATION}:${BUILD_VERSION}" > /dev/null 2>&1; then
+            echo "::error::Image tag '${BUILD_VERSION}' already exists in ECR."
+            exit 1
+          fi
+          echo "BUILD_VERSION=${BUILD_VERSION}" >> "$GITHUB_OUTPUT"
 
       - name: Build
         working-directory: apps/${{ inputs.application }}
@@ -38,7 +51,6 @@ jobs:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           APPLICATION: ${{ inputs.application }}
         run: |
-          BUILD_VERSION="$(cat ./build/version)"
           docker build -t "${ECR_REGISTRY}/yeahboi/apps/${APPLICATION}:${BUILD_VERSION}" -f ./build/Dockerfile .
 
       - name: Push
